// ============================================================
// Mock data for NaijaList Phase 1
// Seed city: Enugu State, Nigeria
// Replace getBusinesses / getBusiness calls with Supabase queries
// when the database is ready.
// ============================================================

import type { Category, State, City, Business, BusinessCard } from './types';

// -----------------------------------------------------------
// Categories (12)
// -----------------------------------------------------------
export const CATEGORIES: Category[] = [
  { id: 'cat-1', name: 'Food & Restaurants', slug: 'food-restaurants', icon: '🍽️', description: 'Restaurants, fast food, canteens, food vendors and caterers.' },
  { id: 'cat-2', name: 'Retail & Shopping', slug: 'retail-shopping', icon: '🛍️', description: 'Supermarkets, boutiques, markets, and online stores.' },
  { id: 'cat-3', name: 'Health & Wellness', slug: 'health-wellness', icon: '🏥', description: 'Clinics, hospitals, pharmacies, gyms and wellness centres.' },
  { id: 'cat-4', name: 'Professional Services', slug: 'professional-services', icon: '💼', description: 'Lawyers, accountants, consultants and business advisors.' },
  { id: 'cat-5', name: 'Auto & Transport', slug: 'auto-transport', icon: '🚗', description: 'Mechanics, spare parts dealers, car hire and logistics.' },
  { id: 'cat-6', name: 'Home Services', slug: 'home-services', icon: '🏠', description: 'Plumbers, electricians, painters, cleaners and contractors.' },
  { id: 'cat-7', name: 'Beauty & Personal Care', slug: 'beauty-personal-care', icon: '💅', description: 'Salons, barbershops, spas, and cosmetics vendors.' },
  { id: 'cat-8', name: 'Education & Tutoring', slug: 'education-tutoring', icon: '📚', description: 'Schools, tutorial centres, coaching and training services.' },
  { id: 'cat-9', name: 'Hotels & Lodging', slug: 'hotels-lodging', icon: '🏨', description: 'Hotels, guesthouses, Airbnb and short-stay apartments.' },
  { id: 'cat-10', name: 'Events & Entertainment', slug: 'events-entertainment', icon: '🎉', description: 'Event planners, DJs, photographers, venues and décor.' },
  { id: 'cat-11', name: 'Finance & Insurance', slug: 'finance-insurance', icon: '🏦', description: 'Microfinance, insurance agents, forex and money transfer.' },
  { id: 'cat-12', name: 'Tech & Digital Services', slug: 'tech-digital', icon: '💻', description: 'Web developers, graphic designers, IT support and repairs.' },
];

// -----------------------------------------------------------
// States
// -----------------------------------------------------------
export const STATES: State[] = [
  { id: 'state-1', name: 'Enugu', slug: 'enugu' },
];

// -----------------------------------------------------------
// Cities
// -----------------------------------------------------------
export const CITIES: City[] = [
  { id: 'city-1', name: 'Enugu', slug: 'enugu-city', stateId: 'state-1', stateName: 'Enugu' },
  { id: 'city-2', name: 'Nsukka', slug: 'nsukka', stateId: 'state-1', stateName: 'Enugu' },
  { id: 'city-3', name: 'Awgu', slug: 'awgu', stateId: 'state-1', stateName: 'Enugu' },
  { id: 'city-4', name: 'Oji River', slug: 'oji-river', stateId: 'state-1', stateName: 'Enugu' },
  { id: 'city-5', name: 'Agbani', slug: 'agbani', stateId: 'state-1', stateName: 'Enugu' },
];

// -----------------------------------------------------------
// Businesses (25 mock listings — Enugu State)
// -----------------------------------------------------------
export const BUSINESSES: Business[] = [
  {
    id: 'biz-1',
    name: "Mama Ngozi's Kitchen",
    slug: 'mama-ngozis-kitchen',
    categoryId: 'cat-1',
    categoryName: 'Food & Restaurants',
    categorySlug: 'food-restaurants',
    cityId: 'city-1',
    cityName: 'Enugu',
    citySlug: 'enugu-city',
    stateId: 'state-1',
    stateName: 'Enugu',
    address: '14 Ogui Road, Enugu',
    phone: '+2348012345678',
    whatsapp: '2348012345678',
    email: 'mamangozi@example.com',
    description: "Authentic Igbo cuisine and Nigerian staples in the heart of Enugu. Serving ofe onugbu, ofe akwu, jollof rice, and fresh fish pepper soup daily. Family-run for over 15 years with warm, homely service.",
    hours: { Mon: '7am–9pm', Tue: '7am–9pm', Wed: '7am–9pm', Thu: '7am–9pm', Fri: '7am–10pm', Sat: '8am–10pm', Sun: '10am–6pm' },
    verificationTier: 'phone',
    isFeatured: true,
    isActive: true,
    coverImageUrl: '/images/placeholder-food.jpg',
    lastConfirmedAt: '2026-07-15T00:00:00Z',
    createdAt: '2026-01-10T00:00:00Z',
    updatedAt: '2026-07-15T00:00:00Z',
    averageRating: 4.7,
    reviewCount: 34,
  },
  {
    id: 'biz-2',
    name: 'Enugu Suites & Guesthouse',
    slug: 'enugu-suites-guesthouse',
    categoryId: 'cat-9',
    categoryName: 'Hotels & Lodging',
    categorySlug: 'hotels-lodging',
    cityId: 'city-1',
    cityName: 'Enugu',
    citySlug: 'enugu-city',
    stateId: 'state-1',
    stateName: 'Enugu',
    address: '7 Independence Layout, Enugu',
    phone: '+2348023456789',
    whatsapp: '2348023456789',
    description: "Clean, affordable accommodation in the Independence Layout area. AC rooms, free Wi-Fi, 24-hour power supply, and secure parking. Perfect for business travellers and families visiting Enugu.",
    hours: { Mon: '24hrs', Tue: '24hrs', Wed: '24hrs', Thu: '24hrs', Fri: '24hrs', Sat: '24hrs', Sun: '24hrs' },
    verificationTier: 'phone',
    isFeatured: true,
    isActive: true,
    coverImageUrl: '/images/placeholder-hotel.jpg',
    lastConfirmedAt: '2026-07-20T00:00:00Z',
    createdAt: '2026-02-01T00:00:00Z',
    updatedAt: '2026-07-20T00:00:00Z',
    averageRating: 4.2,
    reviewCount: 18,
  },
  {
    id: 'biz-3',
    name: 'CodeNaija Tech Hub',
    slug: 'codenaija-tech-hub',
    categoryId: 'cat-12',
    categoryName: 'Tech & Digital Services',
    categorySlug: 'tech-digital',
    cityId: 'city-1',
    cityName: 'Enugu',
    citySlug: 'enugu-city',
    stateId: 'state-1',
    stateName: 'Enugu',
    address: '3 Presidential Road, GRA Enugu',
    phone: '+2348034567890',
    whatsapp: '2348034567890',
    email: 'hello@codenaija.example',
    website: 'https://codenaija.example',
    description: "Enugu's leading web design, mobile app development and IT support company. We help Nigerian SMEs build a strong digital presence. Services: websites, apps, graphic design, social media management, and CCTV installation.",
    hours: { Mon: '8am–6pm', Tue: '8am–6pm', Wed: '8am–6pm', Thu: '8am–6pm', Fri: '8am–5pm', Sat: '9am–2pm', Sun: 'Closed' },
    verificationTier: 'cac',
    isFeatured: true,
    isActive: true,
    coverImageUrl: '/images/placeholder-tech.jpg',
    lastConfirmedAt: '2026-08-01T00:00:00Z',
    createdAt: '2026-01-15T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
    averageRating: 4.9,
    reviewCount: 52,
  },
  {
    id: 'biz-4',
    name: 'ChiChi Beauty Palace',
    slug: 'chichi-beauty-palace',
    categoryId: 'cat-7',
    categoryName: 'Beauty & Personal Care',
    categorySlug: 'beauty-personal-care',
    cityId: 'city-1',
    cityName: 'Enugu',
    citySlug: 'enugu-city',
    stateId: 'state-1',
    stateName: 'Enugu',
    address: '22 Zik Avenue, Uwani, Enugu',
    phone: '+2348045678901',
    whatsapp: '2348045678901',
    description: "Top-rated hair salon and beauty centre in Uwani. Specialising in braiding, weaving, loc maintenance, pedicure, manicure, and bridal makeup. Walk-ins welcome. Book ahead via WhatsApp for guaranteed slots.",
    hours: { Mon: '8am–7pm', Tue: '8am–7pm', Wed: '8am–7pm', Thu: '8am–7pm', Fri: '8am–8pm', Sat: '7am–8pm', Sun: 'Closed' },
    verificationTier: 'phone',
    isFeatured: false,
    isActive: true,
    coverImageUrl: '/images/placeholder-beauty.jpg',
    lastConfirmedAt: '2026-06-30T00:00:00Z',
    createdAt: '2026-03-01T00:00:00Z',
    updatedAt: '2026-06-30T00:00:00Z',
    averageRating: 4.5,
    reviewCount: 27,
  },
  {
    id: 'biz-5',
    name: 'Nkem Auto Workshop',
    slug: 'nkem-auto-workshop',
    categoryId: 'cat-5',
    categoryName: 'Auto & Transport',
    categorySlug: 'auto-transport',
    cityId: 'city-1',
    cityName: 'Enugu',
    citySlug: 'enugu-city',
    stateId: 'state-1',
    stateName: 'Enugu',
    address: 'Obiagu Road, Near Obiagu Round-About, Enugu',
    phone: '+2348056789012',
    whatsapp: '2348056789012',
    description: "Trusted auto mechanic serving Enugu for 12+ years. Specialising in Toyota, Honda, and Kia. Services: engine overhaul, electrical faults, AC repairs, brake jobs, and alignment. Genuine spare parts sourced from Nnewi.",
    hours: { Mon: '7am–6pm', Tue: '7am–6pm', Wed: '7am–6pm', Thu: '7am–6pm', Fri: '7am–6pm', Sat: '8am–4pm', Sun: 'Closed' },
    verificationTier: 'phone',
    isFeatured: false,
    isActive: true,
    coverImageUrl: '/images/placeholder-auto.jpg',
    lastConfirmedAt: '2026-07-01T00:00:00Z',
    createdAt: '2026-02-20T00:00:00Z',
    updatedAt: '2026-07-01T00:00:00Z',
    averageRating: 4.3,
    reviewCount: 19,
  },
  {
    id: 'biz-6',
    name: 'Barrister Ifeoma Okafor & Associates',
    slug: 'barrister-ifeoma-okafor',
    categoryId: 'cat-4',
    categoryName: 'Professional Services',
    categorySlug: 'professional-services',
    cityId: 'city-1',
    cityName: 'Enugu',
    citySlug: 'enugu-city',
    stateId: 'state-1',
    stateName: 'Enugu',
    address: '5 Garden Avenue, GRA, Enugu',
    phone: '+2348067890123',
    whatsapp: '2348067890123',
    email: 'ifeoma.okafor@example.com',
    description: "Full-service law firm specialising in corporate law, land and property transactions, family law, and debt recovery. Over 20 years of experience in Enugu State. Consultations available in-person and via WhatsApp.",
    hours: { Mon: '9am–5pm', Tue: '9am–5pm', Wed: '9am–5pm', Thu: '9am–5pm', Fri: '9am–4pm', Sat: 'By Appointment', Sun: 'Closed' },
    verificationTier: 'cac',
    isFeatured: false,
    isActive: true,
    coverImageUrl: '/images/placeholder-legal.jpg',
    lastConfirmedAt: '2026-08-05T00:00:00Z',
    createdAt: '2026-01-25T00:00:00Z',
    updatedAt: '2026-08-05T00:00:00Z',
    averageRating: 4.8,
    reviewCount: 11,
  },
  {
    id: 'biz-7',
    name: 'Sunrise Pharmacy & Chemist',
    slug: 'sunrise-pharmacy',
    categoryId: 'cat-3',
    categoryName: 'Health & Wellness',
    categorySlug: 'health-wellness',
    cityId: 'city-1',
    cityName: 'Enugu',
    citySlug: 'enugu-city',
    stateId: 'state-1',
    stateName: 'Enugu',
    address: '45 Ogui New Layout, Enugu',
    phone: '+2348078901234',
    whatsapp: '2348078901234',
    description: "NAFDAC-registered pharmacy stocking genuine medications, supplements, baby care products, and medical equipment. A licensed pharmacist is on duty daily. We also accept online orders — send your prescription via WhatsApp.",
    hours: { Mon: '8am–9pm', Tue: '8am–9pm', Wed: '8am–9pm', Thu: '8am–9pm', Fri: '8am–9pm', Sat: '8am–9pm', Sun: '9am–6pm' },
    verificationTier: 'phone',
    isFeatured: false,
    isActive: true,
    coverImageUrl: '/images/placeholder-pharmacy.jpg',
    lastConfirmedAt: '2026-07-28T00:00:00Z',
    createdAt: '2026-02-14T00:00:00Z',
    updatedAt: '2026-07-28T00:00:00Z',
    averageRating: 4.6,
    reviewCount: 23,
  },
  {
    id: 'biz-8',
    name: 'Emeka Electronics & Gadgets',
    slug: 'emeka-electronics',
    categoryId: 'cat-2',
    categoryName: 'Retail & Shopping',
    categorySlug: 'retail-shopping',
    cityId: 'city-1',
    cityName: 'Enugu',
    citySlug: 'enugu-city',
    stateId: 'state-1',
    stateName: 'Enugu',
    address: 'Kingsway Shopping Plaza, Agbani Road, Enugu',
    phone: '+2348089012345',
    whatsapp: '2348089012345',
    description: "Authorised dealer for Samsung, Tecno, Infinix, and itel smartphones. Also selling laptops, accessories, and offering phone repairs. Price-match guarantee on all phones. Delivery available within Enugu metropolis.",
    hours: { Mon: '9am–7pm', Tue: '9am–7pm', Wed: '9am–7pm', Thu: '9am–7pm', Fri: '9am–7pm', Sat: '9am–7pm', Sun: '12pm–5pm' },
    verificationTier: 'phone',
    isFeatured: true,
    isActive: true,
    coverImageUrl: '/images/placeholder-retail.jpg',
    lastConfirmedAt: '2026-08-08T00:00:00Z',
    createdAt: '2026-03-10T00:00:00Z',
    updatedAt: '2026-08-08T00:00:00Z',
    averageRating: 4.4,
    reviewCount: 41,
  },
  {
    id: 'biz-9',
    name: 'BrightStars Tutorial Centre',
    slug: 'brightstars-tutorial-centre',
    categoryId: 'cat-8',
    categoryName: 'Education & Tutoring',
    categorySlug: 'education-tutoring',
    cityId: 'city-2',
    cityName: 'Nsukka',
    citySlug: 'nsukka',
    stateId: 'state-1',
    stateName: 'Enugu',
    address: '11 University Road, Nsukka',
    phone: '+2348090123456',
    whatsapp: '2348090123456',
    email: 'brightstars@example.com',
    description: "Nsukka's most trusted tutorial centre for WAEC, NECO, JAMB, and post-UTME preparation. Subject experts in Mathematics, English, Sciences, and Social Studies. Saturday and holiday coaching available. 90%+ pass rate.",
    hours: { Mon: '2pm–6pm', Tue: '2pm–6pm', Wed: '2pm–6pm', Thu: '2pm–6pm', Fri: '2pm–6pm', Sat: '8am–12pm', Sun: 'Closed' },
    verificationTier: 'cac',
    isFeatured: true,
    isActive: true,
    coverImageUrl: '/images/placeholder-education.jpg',
    lastConfirmedAt: '2026-08-01T00:00:00Z',
    createdAt: '2026-01-20T00:00:00Z',
    updatedAt: '2026-08-01T00:00:00Z',
    averageRating: 4.8,
    reviewCount: 63,
  },
  {
    id: 'biz-10',
    name: 'Jide Event Decorators',
    slug: 'jide-event-decorators',
    categoryId: 'cat-10',
    categoryName: 'Events & Entertainment',
    categorySlug: 'events-entertainment',
    cityId: 'city-1',
    cityName: 'Enugu',
    citySlug: 'enugu-city',
    stateId: 'state-1',
    stateName: 'Enugu',
    address: 'Trans-Ekulu, Enugu',
    phone: '+2348101234567',
    whatsapp: '2348101234567',
    description: "Premium event decoration and planning for weddings, birthdays, corporate events, and funerals in Enugu and South-East Nigeria. Packages include hall decoration, outdoor setup, catering coordination, and photography linkups.",
    hours: { Mon: '9am–6pm', Tue: '9am–6pm', Wed: '9am–6pm', Thu: '9am–6pm', Fri: '9am–6pm', Sat: '8am–8pm', Sun: 'By Appointment' },
    verificationTier: 'phone',
    isFeatured: false,
    isActive: true,
    coverImageUrl: '/images/placeholder-events.jpg',
    lastConfirmedAt: '2026-07-10T00:00:00Z',
    createdAt: '2026-04-01T00:00:00Z',
    updatedAt: '2026-07-10T00:00:00Z',
    averageRating: 4.6,
    reviewCount: 29,
  },
  {
    id: 'biz-11',
    name: 'Cornerstone Plumbing & Electrical',
    slug: 'cornerstone-plumbing-electrical',
    categoryId: 'cat-6',
    categoryName: 'Home Services',
    categorySlug: 'home-services',
    cityId: 'city-1',
    cityName: 'Enugu',
    citySlug: 'enugu-city',
    stateId: 'state-1',
    stateName: 'Enugu',
    address: 'Abakpa Nike, Enugu',
    phone: '+2348112345678',
    whatsapp: '2348112345678',
    description: "Emergency and scheduled plumbing and electrical repairs across Enugu metropolis. Fixing leaking pipes, rewiring, inverter installation, generator servicing, and CCTV setup. Same-day service available. Call or WhatsApp for quotes.",
    hours: { Mon: '7am–8pm', Tue: '7am–8pm', Wed: '7am–8pm', Thu: '7am–8pm', Fri: '7am–8pm', Sat: '8am–6pm', Sun: '10am–4pm' },
    verificationTier: 'phone',
    isFeatured: false,
    isActive: true,
    coverImageUrl: '/images/placeholder-home.jpg',
    lastConfirmedAt: '2026-07-25T00:00:00Z',
    createdAt: '2026-03-15T00:00:00Z',
    updatedAt: '2026-07-25T00:00:00Z',
    averageRating: 4.5,
    reviewCount: 16,
  },
  {
    id: 'biz-12',
    name: 'Enugu Microfinance Bank',
    slug: 'enugu-microfinance-bank',
    categoryId: 'cat-11',
    categoryName: 'Finance & Insurance',
    categorySlug: 'finance-insurance',
    cityId: 'city-1',
    cityName: 'Enugu',
    citySlug: 'enugu-city',
    stateId: 'state-1',
    stateName: 'Enugu',
    address: '1 Okpara Avenue, Enugu',
    phone: '+2348123456789',
    whatsapp: '2348123456789',
    description: "CBN-licensed microfinance bank providing SME loans, savings accounts, cooperative financing, and insurance services for individuals and small businesses in Enugu. Loan decisions in 48 hours with minimal documentation.",
    hours: { Mon: '8am–4pm', Tue: '8am–4pm', Wed: '8am–4pm', Thu: '8am–4pm', Fri: '8am–4pm', Sat: '9am–1pm', Sun: 'Closed' },
    verificationTier: 'cac',
    isFeatured: false,
    isActive: true,
    coverImageUrl: '/images/placeholder-finance.jpg',
    lastConfirmedAt: '2026-08-10T00:00:00Z',
    createdAt: '2026-01-05T00:00:00Z',
    updatedAt: '2026-08-10T00:00:00Z',
    averageRating: 4.1,
    reviewCount: 8,
  },
  {
    id: 'biz-13',
    name: 'Diamond Barbershop',
    slug: 'diamond-barbershop',
    categoryId: 'cat-7',
    categoryName: 'Beauty & Personal Care',
    categorySlug: 'beauty-personal-care',
    cityId: 'city-2',
    cityName: 'Nsukka',
    citySlug: 'nsukka',
    stateId: 'state-1',
    stateName: 'Enugu',
    address: 'University Road, Nsukka',
    phone: '+2348134567890',
    whatsapp: '2348134567890',
    description: "Modern barbershop near UNN campus. Haircut, shape-up, beard grooming, scalp treatment, and dreadlock maintenance. Students get 10% off with valid school ID. Walk-in or book via WhatsApp.",
    hours: { Mon: '8am–8pm', Tue: '8am–8pm', Wed: '8am–8pm', Thu: '8am–8pm', Fri: '8am–8pm', Sat: '8am–8pm', Sun: '10am–6pm' },
    verificationTier: 'none',
    isFeatured: false,
    isActive: true,
    coverImageUrl: '/images/placeholder-barber.jpg',
    lastConfirmedAt: '2026-06-15T00:00:00Z',
    createdAt: '2026-04-10T00:00:00Z',
    updatedAt: '2026-06-15T00:00:00Z',
    averageRating: 4.3,
    reviewCount: 22,
  },
  {
    id: 'biz-14',
    name: 'Obiora Farms & Fresh Produce',
    slug: 'obiora-farms-fresh-produce',
    categoryId: 'cat-2',
    categoryName: 'Retail & Shopping',
    categorySlug: 'retail-shopping',
    cityId: 'city-5',
    cityName: 'Agbani',
    citySlug: 'agbani',
    stateId: 'state-1',
    stateName: 'Enugu',
    address: 'Agbani Market Road, Agbani',
    phone: '+2348145678901',
    whatsapp: '2348145678901',
    description: "Farm-fresh vegetables, fruits, tubers, and grains sourced directly from local farms in Nkanu. Bulk orders for restaurants and caterers welcome. WhatsApp to schedule market pickup or arrange delivery to Enugu metropolis.",
    hours: { Mon: '6am–6pm', Tue: '6am–6pm', Wed: '6am–6pm', Thu: '6am–6pm', Fri: '6am–6pm', Sat: '5am–7pm', Sun: 'Closed' },
    verificationTier: 'none',
    isFeatured: false,
    isActive: true,
    coverImageUrl: '/images/placeholder-farm.jpg',
    lastConfirmedAt: '2026-07-20T00:00:00Z',
    createdAt: '2026-05-01T00:00:00Z',
    updatedAt: '2026-07-20T00:00:00Z',
    averageRating: 4.7,
    reviewCount: 14,
  },
  {
    id: 'biz-15',
    name: 'E-Class Driving School',
    slug: 'eclass-driving-school',
    categoryId: 'cat-5',
    categoryName: 'Auto & Transport',
    categorySlug: 'auto-transport',
    cityId: 'city-1',
    cityName: 'Enugu',
    citySlug: 'enugu-city',
    stateId: 'state-1',
    stateName: 'Enugu',
    address: '30 Agbani Road, Enugu',
    phone: '+2348156789012',
    whatsapp: '2348156789012',
    description: "FRSC-affiliated driving school offering beginner to advanced driving lessons in Enugu. Also providing vehicle licensing, registration renewal, and road-worthiness certificate assistance. Defensive driving courses available.",
    hours: { Mon: '8am–5pm', Tue: '8am–5pm', Wed: '8am–5pm', Thu: '8am–5pm', Fri: '8am–5pm', Sat: '8am–3pm', Sun: 'Closed' },
    verificationTier: 'cac',
    isFeatured: false,
    isActive: true,
    coverImageUrl: '/images/placeholder-driving.jpg',
    lastConfirmedAt: '2026-07-30T00:00:00Z',
    createdAt: '2026-02-28T00:00:00Z',
    updatedAt: '2026-07-30T00:00:00Z',
    averageRating: 4.6,
    reviewCount: 33,
  },
  {
    id: 'biz-16',
    name: 'Excel Health Clinic',
    slug: 'excel-health-clinic',
    categoryId: 'cat-3',
    categoryName: 'Health & Wellness',
    categorySlug: 'health-wellness',
    cityId: 'city-1',
    cityName: 'Enugu',
    citySlug: 'enugu-city',
    stateId: 'state-1',
    stateName: 'Enugu',
    address: '18 Obiagu Road, Enugu',
    phone: '+2348167890123',
    whatsapp: '2348167890123',
    description: "Private clinic providing general practice, malaria treatment, antenatal care, ultrasound scanning, laboratory tests (HIV, Hepatitis, blood sugar, etc.), family planning, and child immunisation. Affordable and confidential.",
    hours: { Mon: '7am–8pm', Tue: '7am–8pm', Wed: '7am–8pm', Thu: '7am–8pm', Fri: '7am–8pm', Sat: '8am–5pm', Sun: '9am–2pm' },
    verificationTier: 'phone',
    isFeatured: false,
    isActive: true,
    coverImageUrl: '/images/placeholder-clinic.jpg',
    lastConfirmedAt: '2026-08-05T00:00:00Z',
    createdAt: '2026-03-20T00:00:00Z',
    updatedAt: '2026-08-05T00:00:00Z',
    averageRating: 4.4,
    reviewCount: 31,
  },
  {
    id: 'biz-17',
    name: 'Peak Suya & Grill',
    slug: 'peak-suya-grill',
    categoryId: 'cat-1',
    categoryName: 'Food & Restaurants',
    categorySlug: 'food-restaurants',
    cityId: 'city-2',
    cityName: 'Nsukka',
    citySlug: 'nsukka',
    stateId: 'state-1',
    stateName: 'Enugu',
    address: 'Behind Shoprite Area, Nsukka',
    phone: '+2348178901234',
    whatsapp: '2348178901234',
    description: "Nsukka's hottest suya spot. Serving fresh beef suya, chicken suya, isi-ewu, and nkwobi every evening from 5pm. Also catering for parties and events. Order ahead via WhatsApp for large orders.",
    hours: { Mon: '5pm–11pm', Tue: '5pm–11pm', Wed: '5pm–11pm', Thu: '5pm–11pm', Fri: '5pm–12am', Sat: '4pm–12am', Sun: '5pm–10pm' },
    verificationTier: 'none',
    isFeatured: false,
    isActive: true,
    coverImageUrl: '/images/placeholder-suya.jpg',
    lastConfirmedAt: '2026-07-12T00:00:00Z',
    createdAt: '2026-05-15T00:00:00Z',
    updatedAt: '2026-07-12T00:00:00Z',
    averageRating: 4.8,
    reviewCount: 47,
  },
  {
    id: 'biz-18',
    name: 'Eze & Sons Paint & Hardware',
    slug: 'eze-sons-paint-hardware',
    categoryId: 'cat-6',
    categoryName: 'Home Services',
    categorySlug: 'home-services',
    cityId: 'city-1',
    cityName: 'Enugu',
    citySlug: 'enugu-city',
    stateId: 'state-1',
    stateName: 'Enugu',
    address: 'New Market Road, Enugu',
    phone: '+2348189012345',
    whatsapp: '2348189012345',
    description: "Stockists of Berger, Dulux, Crown, and local quality paints. Also selling tiles, sanitary fittings, roofing sheets, nails, cement, and building hardware. Bulk order discounts available. Delivery within Enugu.",
    hours: { Mon: '8am–6pm', Tue: '8am–6pm', Wed: '8am–6pm', Thu: '8am–6pm', Fri: '8am–6pm', Sat: '8am–5pm', Sun: 'Closed' },
    verificationTier: 'phone',
    isFeatured: false,
    isActive: true,
    coverImageUrl: '/images/placeholder-hardware.jpg',
    lastConfirmedAt: '2026-07-08T00:00:00Z',
    createdAt: '2026-04-20T00:00:00Z',
    updatedAt: '2026-07-08T00:00:00Z',
    averageRating: 4.2,
    reviewCount: 9,
  },
  {
    id: 'biz-19',
    name: 'Photo Queen Studio',
    slug: 'photo-queen-studio',
    categoryId: 'cat-10',
    categoryName: 'Events & Entertainment',
    categorySlug: 'events-entertainment',
    cityId: 'city-1',
    cityName: 'Enugu',
    citySlug: 'enugu-city',
    stateId: 'state-1',
    stateName: 'Enugu',
    address: '8 Agbani Road, Enugu',
    phone: '+2348190123456',
    whatsapp: '2348190123456',
    description: "Professional photographer covering weddings, traditional marriages, birthday parties, corporate events, and passport photos in Enugu. Same-day photo editing and delivery. Drone shots available for premium packages.",
    hours: { Mon: '9am–6pm', Tue: '9am–6pm', Wed: '9am–6pm', Thu: '9am–6pm', Fri: '9am–6pm', Sat: '8am–7pm', Sun: 'By Appointment' },
    verificationTier: 'phone',
    isFeatured: false,
    isActive: true,
    coverImageUrl: '/images/placeholder-photo.jpg',
    lastConfirmedAt: '2026-07-22T00:00:00Z',
    createdAt: '2026-05-08T00:00:00Z',
    updatedAt: '2026-07-22T00:00:00Z',
    averageRating: 4.7,
    reviewCount: 38,
  },
  {
    id: 'biz-20',
    name: 'Trust Accounting & Tax Services',
    slug: 'trust-accounting-tax',
    categoryId: 'cat-4',
    categoryName: 'Professional Services',
    categorySlug: 'professional-services',
    cityId: 'city-1',
    cityName: 'Enugu',
    citySlug: 'enugu-city',
    stateId: 'state-1',
    stateName: 'Enugu',
    address: '14 Ogui Road, Enugu',
    phone: '+2348201234567',
    whatsapp: '2348201234567',
    email: 'trust.accounting@example.com',
    description: "Chartered accounting firm offering business registration (CAC), tax filing (FIRS, SIRS), auditing, payroll management, and financial consulting for SMEs in Enugu. First consultation is free. WhatsApp for quick inquiries.",
    hours: { Mon: '8am–5pm', Tue: '8am–5pm', Wed: '8am–5pm', Thu: '8am–5pm', Fri: '8am–4pm', Sat: 'By Appointment', Sun: 'Closed' },
    verificationTier: 'cac',
    isFeatured: false,
    isActive: true,
    coverImageUrl: '/images/placeholder-accounting.jpg',
    lastConfirmedAt: '2026-08-07T00:00:00Z',
    createdAt: '2026-02-10T00:00:00Z',
    updatedAt: '2026-08-07T00:00:00Z',
    averageRating: 4.9,
    reviewCount: 7,
  },
  {
    id: 'biz-21',
    name: 'Uche Logistics & Haulage',
    slug: 'uche-logistics-haulage',
    categoryId: 'cat-5',
    categoryName: 'Auto & Transport',
    categorySlug: 'auto-transport',
    cityId: 'city-1',
    cityName: 'Enugu',
    citySlug: 'enugu-city',
    stateId: 'state-1',
    stateName: 'Enugu',
    address: 'Enugu–Onitsha Expressway, Enugu',
    phone: '+2348212345678',
    whatsapp: '2348212345678',
    description: "Inter-state and intra-city logistics, moving services, and haulage across South-East and South-South Nigeria. Mini vans, trucks, and flatbed vehicles available. Fragile cargo handling and furniture moving specialists.",
    hours: { Mon: '6am–8pm', Tue: '6am–8pm', Wed: '6am–8pm', Thu: '6am–8pm', Fri: '6am–8pm', Sat: '6am–6pm', Sun: 'By Request' },
    verificationTier: 'phone',
    isFeatured: false,
    isActive: true,
    coverImageUrl: '/images/placeholder-logistics.jpg',
    lastConfirmedAt: '2026-07-18T00:00:00Z',
    createdAt: '2026-04-05T00:00:00Z',
    updatedAt: '2026-07-18T00:00:00Z',
    averageRating: 4.3,
    reviewCount: 12,
  },
  {
    id: 'biz-22',
    name: 'Grace Maternity & Child Care',
    slug: 'grace-maternity-child-care',
    categoryId: 'cat-3',
    categoryName: 'Health & Wellness',
    categorySlug: 'health-wellness',
    cityId: 'city-3',
    cityName: 'Awgu',
    citySlug: 'awgu',
    stateId: 'state-1',
    stateName: 'Enugu',
    address: 'Awgu Town, Off Enugu–Port Harcourt Road',
    phone: '+2348223456789',
    whatsapp: '2348223456789',
    description: "Specialist maternity clinic and paediatric centre in Awgu serving women and children in Awgu LGA. Services include antenatal, safe delivery, postnatal care, immunisation, and family planning.",
    hours: { Mon: '8am–6pm', Tue: '8am–6pm', Wed: '8am–6pm', Thu: '8am–6pm', Fri: '8am–6pm', Sat: '8am–2pm', Sun: 'Emergencies Only' },
    verificationTier: 'phone',
    isFeatured: false,
    isActive: true,
    coverImageUrl: '/images/placeholder-maternity.jpg',
    lastConfirmedAt: '2026-07-03T00:00:00Z',
    createdAt: '2026-06-01T00:00:00Z',
    updatedAt: '2026-07-03T00:00:00Z',
    averageRating: 4.6,
    reviewCount: 15,
  },
  {
    id: 'biz-23',
    name: 'Harmony Guest Inn',
    slug: 'harmony-guest-inn',
    categoryId: 'cat-9',
    categoryName: 'Hotels & Lodging',
    categorySlug: 'hotels-lodging',
    cityId: 'city-4',
    cityName: 'Oji River',
    citySlug: 'oji-river',
    stateId: 'state-1',
    stateName: 'Enugu',
    address: 'Oji River Town, Enugu–Onitsha Road',
    phone: '+2348234567890',
    whatsapp: '2348234567890',
    description: "Budget-friendly guesthouse with clean rooms, constant power supply, and good road network access in Oji River. Ideal for road travellers and business visitors. Breakfast available. Book ahead for weekends.",
    hours: { Mon: '24hrs', Tue: '24hrs', Wed: '24hrs', Thu: '24hrs', Fri: '24hrs', Sat: '24hrs', Sun: '24hrs' },
    verificationTier: 'none',
    isFeatured: false,
    isActive: true,
    coverImageUrl: '/images/placeholder-guesthouse.jpg',
    lastConfirmedAt: '2026-06-20T00:00:00Z',
    createdAt: '2026-06-10T00:00:00Z',
    updatedAt: '2026-06-20T00:00:00Z',
    averageRating: 4.0,
    reviewCount: 6,
  },
  {
    id: 'biz-24',
    name: 'Nnenna Fashion House',
    slug: 'nnenna-fashion-house',
    categoryId: 'cat-2',
    categoryName: 'Retail & Shopping',
    categorySlug: 'retail-shopping',
    cityId: 'city-1',
    cityName: 'Enugu',
    citySlug: 'enugu-city',
    stateId: 'state-1',
    stateName: 'Enugu',
    address: '6 Coal City Mall, Enugu',
    phone: '+2348245678901',
    whatsapp: '2348245678901',
    description: "Fashion boutique specialising in Ankara fabric, ready-to-wear native wear, corporate attire and custom tailoring for men, women, and children in Enugu. Fast turnaround — 3 working days for custom outfits. Order fabric online.",
    hours: { Mon: '10am–7pm', Tue: '10am–7pm', Wed: '10am–7pm', Thu: '10am–7pm', Fri: '10am–7pm', Sat: '10am–8pm', Sun: '12pm–5pm' },
    verificationTier: 'phone',
    isFeatured: false,
    isActive: true,
    coverImageUrl: '/images/placeholder-fashion.jpg',
    lastConfirmedAt: '2026-08-09T00:00:00Z',
    createdAt: '2026-03-25T00:00:00Z',
    updatedAt: '2026-08-09T00:00:00Z',
    averageRating: 4.5,
    reviewCount: 24,
  },
  {
    id: 'biz-25',
    name: 'Apex Computer Training Centre',
    slug: 'apex-computer-training',
    categoryId: 'cat-8',
    categoryName: 'Education & Tutoring',
    categorySlug: 'education-tutoring',
    cityId: 'city-1',
    cityName: 'Enugu',
    citySlug: 'enugu-city',
    stateId: 'state-1',
    stateName: 'Enugu',
    address: '2nd Floor, Zik Avenue Plaza, Enugu',
    phone: '+2348256789012',
    whatsapp: '2348256789012',
    email: 'apex.training@example.com',
    description: "Practical ICT training for beginners and professionals in Enugu. Courses: Microsoft Office, graphic design (Photoshop, CorelDraw), web design (HTML/CSS), digital marketing, and data entry. Certificates issued. Weekday & weekend batches.",
    hours: { Mon: '8am–6pm', Tue: '8am–6pm', Wed: '8am–6pm', Thu: '8am–6pm', Fri: '8am–5pm', Sat: '9am–3pm', Sun: 'Closed' },
    verificationTier: 'phone',
    isFeatured: false,
    isActive: true,
    coverImageUrl: '/images/placeholder-computer.jpg',
    lastConfirmedAt: '2026-08-03T00:00:00Z',
    createdAt: '2026-04-15T00:00:00Z',
    updatedAt: '2026-08-03T00:00:00Z',
    averageRating: 4.6,
    reviewCount: 20,
  },
];

// ============================================================
// Helper functions — data access layer
// When Supabase is wired up, replace these with DB queries.
// ============================================================

export function getCategories(): Category[] {
  return CATEGORIES.map((cat) => ({
    ...cat,
    businessCount: BUSINESSES.filter((b) => b.categoryId === cat.id && b.isActive).length,
  }));
}

export function getCategoryBySlug(slug: string): Category | undefined {
  return CATEGORIES.find((c) => c.slug === slug);
}

export function getStates(): State[] {
  return STATES;
}

export function getCities(): City[] {
  return CITIES.map((city) => ({
    ...city,
    businessCount: BUSINESSES.filter((b) => b.cityId === city.id && b.isActive).length,
  }));
}

export function getCityBySlug(slug: string): City | undefined {
  return CITIES.find((c) => c.slug === slug);
}

export function getBusinesses(filters: {
  categorySlug?: string;
  citySlug?: string;
  featured?: boolean;
  limit?: number;
} = {}): BusinessCard[] {
  let results = BUSINESSES.filter((b) => b.isActive);

  if (filters.categorySlug) {
    results = results.filter((b) => b.categorySlug === filters.categorySlug);
  }
  if (filters.citySlug) {
    results = results.filter((b) => b.citySlug === filters.citySlug);
  }
  if (filters.featured !== undefined) {
    results = results.filter((b) => b.isFeatured === filters.featured);
  }
  if (filters.limit) {
    results = results.slice(0, filters.limit);
  }

  return results.map((b) => ({
    id: b.id,
    name: b.name,
    slug: b.slug,
    categoryName: b.categoryName,
    categorySlug: b.categorySlug,
    cityName: b.cityName,
    citySlug: b.citySlug,
    stateName: b.stateName,
    address: b.address,
    phone: b.phone,
    whatsapp: b.whatsapp,
    verificationTier: b.verificationTier,
    isFeatured: b.isFeatured,
    coverImageUrl: b.coverImageUrl,
    averageRating: b.averageRating,
    reviewCount: b.reviewCount,
    lastConfirmedAt: b.lastConfirmedAt,
  }));
}

export function getBusinessBySlug(slug: string): Business | undefined {
  return BUSINESSES.find((b) => b.slug === slug && b.isActive);
}

export function getFeaturedBusinesses(limit = 6): BusinessCard[] {
  return getBusinesses({ featured: true, limit });
}

export function getRelatedBusinesses(business: Business, limit = 3): BusinessCard[] {
  return getBusinesses({ categorySlug: business.categorySlug, limit: limit + 1 }).filter(
    (b) => b.slug !== business.slug
  ).slice(0, limit);
}
